services:
  app:
    build: .
    container_name: my-server-app
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./storage:/app/storage # Підключаемо volume для зберігання даних
    restart: always
